2022-11-02 17:21:03,765:DEBUG:certbot._internal.main:certbot version: 1.27.0
2022-11-02 17:21:03,766:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/bin/certbot
2022-11-02 17:21:03,766:DEBUG:certbot._internal.main:Arguments: ['--config', '/etc/letsencrypt.ini', '--cert-name', 'npm-2', '--agree-tos', '--authenticator', 'webroot', '--email', 'admin@proxy.com', '--preferred-challenges', 'dns,http', '--domains', 'cadiaz.mavi.mx']
2022-11-02 17:21:03,766:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2022-11-02 17:21:03,953:DEBUG:certbot._internal.log:Root logging level set at 30
2022-11-02 17:21:03,962:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2022-11-02 17:21:03,966:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: Authenticator, Plugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7f6ade9a8be0>
Prep: True
2022-11-02 17:21:03,967:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7f6ade9a8be0> and installer None
2022-11-02 17:21:03,967:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2022-11-02 17:21:04,024:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/805934297', new_authzr_uri=None, terms_of_service=None), f102bd3274b2c8d2aa11fb83c84c6d12, Meta(creation_dt=datetime.datetime(2022, 11, 2, 17, 20, 38, tzinfo=<UTC>), creation_host='cada018db9f5', register_to_eff=None))>
2022-11-02 17:21:04,025:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2022-11-02 17:21:04,027:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2022-11-02 17:21:04,295:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 659
2022-11-02 17:21:04,297:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 02 Nov 2022 17:21:04 GMT
Content-Type: application/json
Content-Length: 659
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "PSZNsBpi5Mk": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2022-11-02 17:21:04,299:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for cadiaz.mavi.mx
2022-11-02 17:21:04,309:DEBUG:certbot.crypto_util:Generating ECDSA key (2048 bits): /etc/letsencrypt/keys/0001_key-certbot.pem
2022-11-02 17:21:04,318:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0001_csr-certbot.pem
2022-11-02 17:21:04,320:DEBUG:acme.client:Requesting fresh nonce
2022-11-02 17:21:04,320:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2022-11-02 17:21:04,394:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2022-11-02 17:21:04,394:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 02 Nov 2022 17:21:04 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: F977FbhLiPHBF4VtdIZdaGN1znTYjXNEO7AK_KS2TFUN0SQ
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2022-11-02 17:21:04,395:DEBUG:acme.client:Storing nonce: F977FbhLiPHBF4VtdIZdaGN1znTYjXNEO7AK_KS2TFUN0SQ
2022-11-02 17:21:04,395:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "cadiaz.mavi.mx"\n    }\n  ]\n}'
2022-11-02 17:21:04,398:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvODA1OTM0Mjk3IiwgIm5vbmNlIjogIkY5NzdGYmhMaVBIQkY0VnRkSVpkYUdOMXpuVFlqWE5FTzdBS19LUzJURlVOMFNRIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctb3JkZXIifQ",
  "signature": "QT6P_XpeEhPp_JUNi6UnC1QDqkHMH5UT0J8MsuZRHGx_0qy7aNWV8qd9okzdvPKamFoOvBUyV28GMKbfH8pmQTeYt4jX6P3ko4ekC9LGHIRvPBUEVctGZ6A24MebzrusXnFZnPTfln9YZx9Js0eEoccd-A5kMipLHBM2SME_H_ko0howJji2jplZ5Bjgnma8Vob7Vw2jkf0k6KVISTxnc5_ofeYfYw9lAqQKGYL02C47iNuSVUXsFjL93tLTFWvvJOyBYCcLv-gk0aolbYGNMQRVjB2JURuxZIhe6DsPSx45bakdAiccqf1DHIgRQpl1mksLzvmOspXJAFgUl9aT_w",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogImNhZGlhei5tYXZpLm14IgogICAgfQogIF0KfQ"
}
2022-11-02 17:21:04,525:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 339
2022-11-02 17:21:04,526:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Wed, 02 Nov 2022 17:21:04 GMT
Content-Type: application/json
Content-Length: 339
Connection: keep-alive
Boulder-Requester: 805934297
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/805934297/140324374987
Replay-Nonce: C400r4Viy9yPfMHtRJxgxnRyQebUmIopwup0b0XAJlwyeGQ
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2022-11-09T17:21:04Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "cadiaz.mavi.mx"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/171620722167"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/805934297/140324374987"
}
2022-11-02 17:21:04,527:DEBUG:acme.client:Storing nonce: C400r4Viy9yPfMHtRJxgxnRyQebUmIopwup0b0XAJlwyeGQ
2022-11-02 17:21:04,528:DEBUG:acme.client:JWS payload:
b''
2022-11-02 17:21:04,530:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/171620722167:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvODA1OTM0Mjk3IiwgIm5vbmNlIjogIkM0MDByNFZpeTl5UGZNSHRSSnhneG5SeVFlYlVtSW9wd3VwMGIwWEFKbHd5ZUdRIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My8xNzE2MjA3MjIxNjcifQ",
  "signature": "hiyyTDECMJPQf3maRAetyAWMFnet2NphbSU2v-qGVv6D-BIQU65Wan1ChP2XRmhd2MJvu7d9DdEVkZGEfC5MXlXmdKQc7g4rmd75F6f6cIZvvl1ESTSyXWZRvkkR25ad2OWEKy9-nHKjgzQK1YDpj255R2ZaWrWdvE4tisuCYWy6EXK-8_1SloR4LeJxVCTdTSPR0V0i7jtHhAJ150nLJnpBHV4fh1fjQFYmZFvI6Sfh6RnrUCxCTmjfI5Ov4QBCQgZPgW9v70YqNPAOSSMaxoqHgqhttXPKbtPNqAw2FvoDPmchWz7bcLd7Sy__JutW1j41oXj0gOX57DqTqEpEKQ",
  "payload": ""
}
2022-11-02 17:21:04,607:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/171620722167 HTTP/1.1" 200 798
2022-11-02 17:21:04,608:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 02 Nov 2022 17:21:04 GMT
Content-Type: application/json
Content-Length: 798
Connection: keep-alive
Boulder-Requester: 805934297
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: A5FEiaqtEj7tMerTBpNBKQSy9FMSjuE1pt_vOM_ufjXisJ4
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "cadiaz.mavi.mx"
  },
  "status": "pending",
  "expires": "2022-11-09T17:21:04Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/171620722167/WWCNNg",
      "token": "stRQRx2l1SdRceIOjWyLePZCUb4m_h4Dr3aG5bWuhDc"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/171620722167/lFz3JA",
      "token": "stRQRx2l1SdRceIOjWyLePZCUb4m_h4Dr3aG5bWuhDc"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/171620722167/ZCfYrg",
      "token": "stRQRx2l1SdRceIOjWyLePZCUb4m_h4Dr3aG5bWuhDc"
    }
  ]
}
2022-11-02 17:21:04,609:DEBUG:acme.client:Storing nonce: A5FEiaqtEj7tMerTBpNBKQSy9FMSjuE1pt_vOM_ufjXisJ4
2022-11-02 17:21:04,610:INFO:certbot._internal.auth_handler:Performing the following challenges:
2022-11-02 17:21:04,610:INFO:certbot._internal.auth_handler:http-01 challenge for cadiaz.mavi.mx
2022-11-02 17:21:04,611:INFO:certbot._internal.plugins.webroot:Using the webroot path /data/letsencrypt-acme-challenge for all unmatched domains.
2022-11-02 17:21:04,611:DEBUG:certbot._internal.plugins.webroot:Creating root challenges validation dir at /data/letsencrypt-acme-challenge/.well-known/acme-challenge
2022-11-02 17:21:04,624:DEBUG:certbot._internal.plugins.webroot:Attempting to save validation to /data/letsencrypt-acme-challenge/.well-known/acme-challenge/stRQRx2l1SdRceIOjWyLePZCUb4m_h4Dr3aG5bWuhDc
2022-11-02 17:21:04,629:DEBUG:acme.client:JWS payload:
b'{}'
2022-11-02 17:21:04,630:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall-v3/171620722167/WWCNNg:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvODA1OTM0Mjk3IiwgIm5vbmNlIjogIkE1RkVpYXF0RWo3dE1lclRCcE5CS1FTeTlGTVNqdUUxcHRfdk9NX3Vmalhpc0o0IiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9jaGFsbC12My8xNzE2MjA3MjIxNjcvV1dDTk5nIn0",
  "signature": "TKkaO2nK5kK0o3Z-MGxz2JhCZFXU_Ww4-UzR1Z-H1ioxW1A3vHPNXxAoyHhoMlmzx1oIVOxYq579id6Tuis6sQl7mKdS_6fqq22RmHm0pl9wJMEF3YzNeiU-qpBTXcEosrzhlVN4ulkADOtFedRlKJQuum8CVV9u4nNgCwmEM-3yzYkQGoyFcyRE7p42q_efKyWIqMrjxbPJ4PTa1rg5C03VyfSuc3vQ8onxciuwjsEfeHFVwjY4yTrnr0qLInlwnCyt1hEFrka7Y5FtTCbQCLnNUWkPBOZdZ54E-jRLZM4YcI1c9oZQJBRcQ5g0qjoVigWa8I_L0XiOBObRImr26Q",
  "payload": "e30"
}
2022-11-02 17:21:04,707:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/171620722167/WWCNNg HTTP/1.1" 200 187
2022-11-02 17:21:04,708:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 02 Nov 2022 17:21:04 GMT
Content-Type: application/json
Content-Length: 187
Connection: keep-alive
Boulder-Requester: 805934297
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz-v3/171620722167>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/171620722167/WWCNNg
Replay-Nonce: A5FEd_kNFc0IblW6fD_Qkb0oULWEzZ35rRCF5cCVNWoYdVw
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/171620722167/WWCNNg",
  "token": "stRQRx2l1SdRceIOjWyLePZCUb4m_h4Dr3aG5bWuhDc"
}
2022-11-02 17:21:04,708:DEBUG:acme.client:Storing nonce: A5FEd_kNFc0IblW6fD_Qkb0oULWEzZ35rRCF5cCVNWoYdVw
2022-11-02 17:21:04,710:INFO:certbot._internal.auth_handler:Waiting for verification...
2022-11-02 17:21:05,711:DEBUG:acme.client:JWS payload:
b''
2022-11-02 17:21:05,713:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/171620722167:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvODA1OTM0Mjk3IiwgIm5vbmNlIjogIkE1RkVkX2tORmMwSWJsVzZmRF9Ra2Iwb1VMV0V6WjM1clJDRjVjQ1ZOV29ZZFZ3IiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My8xNzE2MjA3MjIxNjcifQ",
  "signature": "VPi7jIy63fi1P302E7xUij8VnLW9voLPi5o4SIwpZsjvTTl6zgBoqkMUlL4vZHwC1PL7OU-mtPvGmjEYBFzh51gyJVHfTAXbYADM7ALHbfCjyLP4UBmFQsW6zCs0B9A1fmpdN738UKq7bES7CQvUQ09sl-iNHi0TCKs-9Jm3YEMJEoj4ZYS5t7oL1AMOtpjQvD5PSW5GA92o1aiDeJPDo1W29e-cRhyiARDU5RBeNFp0GukgZLxJpeEJKSpEkBkz1inNMV_zS3N_Wl8sO1-kL2NZuYXQrBY3kvp5uQRzpIFbbwac4mWVcMxoKk41p7xscDX3FozkaNOlkCFkHR76Nw",
  "payload": ""
}
2022-11-02 17:21:05,788:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/171620722167 HTTP/1.1" 200 741
2022-11-02 17:21:05,789:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 02 Nov 2022 17:21:05 GMT
Content-Type: application/json
Content-Length: 741
Connection: keep-alive
Boulder-Requester: 805934297
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 853FStfQ_0jM8T2mtCz60fkK0DWpdJuxBL9MffYWFi_AzCc
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "cadiaz.mavi.mx"
  },
  "status": "invalid",
  "expires": "2022-11-09T17:21:04Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:dns",
        "detail": "DNS problem: NXDOMAIN looking up A for cadiaz.mavi.mx - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for cadiaz.mavi.mx - check that a DNS record exists for this domain",
        "status": 400
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/171620722167/WWCNNg",
      "token": "stRQRx2l1SdRceIOjWyLePZCUb4m_h4Dr3aG5bWuhDc",
      "validated": "2022-11-02T17:21:04Z"
    }
  ]
}
2022-11-02 17:21:05,789:DEBUG:acme.client:Storing nonce: 853FStfQ_0jM8T2mtCz60fkK0DWpdJuxBL9MffYWFi_AzCc
2022-11-02 17:21:05,790:INFO:certbot._internal.auth_handler:Challenge failed for domain cadiaz.mavi.mx
2022-11-02 17:21:05,790:INFO:certbot._internal.auth_handler:http-01 challenge for cadiaz.mavi.mx
2022-11-02 17:21:05,790:DEBUG:certbot._internal.display.obj:Notifying user: 
Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: cadiaz.mavi.mx
  Type:   dns
  Detail: DNS problem: NXDOMAIN looking up A for cadiaz.mavi.mx - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for cadiaz.mavi.mx - check that a DNS record exists for this domain

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.

2022-11-02 17:21:05,791:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/certbot/_internal/auth_handler.py", line 106, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/usr/lib/python3.9/site-packages/certbot/_internal/auth_handler.py", line 206, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2022-11-02 17:21:05,791:DEBUG:certbot._internal.error_handler:Calling registered functions
2022-11-02 17:21:05,792:INFO:certbot._internal.auth_handler:Cleaning up challenges
2022-11-02 17:21:05,792:DEBUG:certbot._internal.plugins.webroot:Removing /data/letsencrypt-acme-challenge/.well-known/acme-challenge/stRQRx2l1SdRceIOjWyLePZCUb4m_h4Dr3aG5bWuhDc
2022-11-02 17:21:05,800:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2022-11-02 17:21:05,800:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/usr/lib/python3.9/site-packages/certbot/_internal/main.py", line 1744, in main
    return config.func(config, plugins)
  File "/usr/lib/python3.9/site-packages/certbot/_internal/main.py", line 1591, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/lib/python3.9/site-packages/certbot/_internal/main.py", line 141, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python3.9/site-packages/certbot/_internal/client.py", line 513, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python3.9/site-packages/certbot/_internal/client.py", line 441, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/lib/python3.9/site-packages/certbot/_internal/client.py", line 493, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
  File "/usr/lib/python3.9/site-packages/certbot/_internal/auth_handler.py", line 106, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/usr/lib/python3.9/site-packages/certbot/_internal/auth_handler.py", line 206, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2022-11-02 17:21:05,802:ERROR:certbot._internal.log:Some challenges have failed.
